/*
             AUTHOR:   Khuram Haseeb
            SUMMARY:   its authentication const file that have default define variables used 
                       in different action,saga,reducer file to perform specific function.
*/
export default 
{
    //  making the constant varible for get language api
    LANGUAGE_REQUEST: "LANGUAGE_REQUEST",
    LANGUAGE_SUCCESS: "LANGUAGE_SUCCESS",
    LANGUAGE_FAILURE: "LANGUAGE_FAILURE",

    //  its storage the language from the api request
    LANGUAGE_STORE_REQUEST: "LANGUAGE_STORE_REQUEST",
    LANGUAGE_STORE_SUCCESS: "LANGUAGE_STORE_SUCCESS",
    LANGUAGE_STORE_FAILURE: "LANGUAGE_STORE_FAILURE",

    //  vaiable of the  sms service for authenfication
    AUTH_SEND_SMS_REQUEST: "AUTH_SEND_SMS_REQUEST",
    AUTH_SEND_SMS_SUCCESS: "AUTH_SEND_SMS_SUCCESS",
    AUTH_SEND_SMS_FAILURE: "AUTH_SEND_SMS_FAILURE",

    // variable of the sms 4 digit received from mobile
    OTP_VERIFY_REQUEST: "OTP_VERIFY_REQUEST",
    OTP_VERIFY_SUCCESS: "OTP_VERIFY_SUCCESS",
    OTP_VERIFY_FAILURE: "OTP_VERIFY_FAILURE",

    // variable of the privacy request 
    GET_PRIVACY_REQUEST: "GET_PRIVACY_REQUEST",
    GET_PRIVACY_SUCCESS: "GET_PRIVACY_SUCCESS",
    GET_PRIVACY_FAILURE: "GET_PRIVACY_FAILURE",

    //  get request of the term condition api
    GET_TERMS_REQUEST: "GET_TERMS_REQUEST",
    GET_TERMS_SUCCESS: "GET_TERMS_SUCCESS",
    GET_TERMS_FAILURE: "GET_TERMS_FAILURE",

    // voice call api request variable 
    VOICE_CALL_REQUEST: "VOICE_CALL_REQUEST",
    VOICE_CALL_SUCCESS: "VOICE_CALL_SUCCESS",
    VOICE_CALL_FAILURE: "VOICE_CALL_FAILURE",

    //  user profile Image upload type
    USER_PROFILE_IMAGE_UPLOAD_REQUEST: "USER_PROFILE_IMAGE_UPLOAD_REQUEST",
    USER_PROFILE_IMAGE_UPLOAD_SUCCESS: "USER_PROFILE_IMAGE_UPLOAD_SUCCESS",
    USER_PROFILE_IMAGE_UPLOAD_FAILURE: "USER_PROFILE_IMAGE_UPLOAD_FAILURE",

    //  user profile Set up data type
    USER_PROFILE_SETUP_DATA_REQUEST: "USER_PROFILE_SETUP_DATA_REQUEST",
    USER_PROFILE_SETUP_DATA_SUCCESS: "USER_PROFILE_SETUP_DATA_SUCCESS",
    USER_PROFILE_SETUP_DATA_FAILURE: "USER_PROFILE_SETUP_DATA_FAILURE",

    // when a user open the app the static data will be load in the front end side
    GET_SPLASH_SCREEN_REQUEST: "GET_SPLASH_SCREEN_REQUEST",
    GET_SPLASH_SCREEN_SUCCESS: "GET_SPLASH_SCREEN_SUCCESS",
    GET_SPLASH_SCREEN_FAILURE: "GET_SPLASH_SCREEN_FAILURE",

    //  User Verify Otp variable for login/signup user
    VERIFY_OTP_REQUEST: "VERIFY_OTP_REQUEST",
    VERIFY_OTP_SUCCESS: "VERIFY_OTP_SUCCESS",
    VERIFY_OTP_FAILURE: "VERIFY_OTP_FAILURE",

    //  Resend  Verify Otp variable for the sms service
    RESEND_VERIFY_OTP_REQUEST: "RESEND_VERIFY_OTP_REQUEST",
    RESEND_VERIFY_OTP_SUCCESS: "RESEND_VERIFY_OTP_SUCCESS",
    RESEND_VERIFY_OTP_FAILURE: "RESEND_VERIFY_OTP_FAILURE",

    //  get slider static data from the server 
    GET_SLIDER_IMAGE_REQUEST:"GET_SLIDER_IMAGE_REQUEST",
    GET_SLIDER_IMAGE_SUCCESS:"GET_SLIDER_IMAGE_SUCCESS",
    GET_SLIDER_IMAGE_FAILURE:"GET_SLIDER_IMAGE_FAILURE",

    //  user login with phone number
    CUSTOMER_REGISTRATION_REQUEST:"CUSTOMER_REGISTRATION_REQUEST",
    CUSTOMER_REGISTRATION_SUCCESS:"CUSTOMER_REGISTRATION_SUCCESS",
    CUSTOMER_REGISTRATION_FAILURE:"USTOMER_REGISTRATION_FAILURE",

    //  user login with social media 
    SOCIAL_REGISTRATION_REQUEST:"SOCIAL_REGISTRATION_REQUEST",
    SOCIAL_REGISTRATION_SUCCESS:"SOCIAL_REGISTRATION_SUCCESS",
    SOCIAL_REGISTRATION_FAILURE: "SOCIAL_REGISTRATION_FAILURE",

    //  user sen dthe social media id to server
    SOCIAL_MEDIA_ID_REQUEST:"SOCIAL_MEDIA_ID_REQUEST",
    SOCIAL_MEDIA_ID_SUCCESS:"SOCIAL_MEDIA_ID_SUCCESS",
    SOCIAL_MEDIA_ID_FAILURE: "SOCIAL_MEDIA_ID_FAILURE",
    
   //   get country list data in the login screen 
    COUNTRY_CODE_REQUEST:"COUNTRY_CODE_REQUEST",
    COUNTRY_CODE_SUCCESS:"COUNTRY_CODE_SUCCESS",
    COUNTRY_CODE_FAILURE:"COUNTRY_CODE_FAILURE",

   //   get signup static data load for whole application
    STATIC_SIGNUP_DATALOAD_REQUEST:"STATIC_SIGNUP_DATALOAD_REQUEST",
    STATIC_SIGNUP_DATALOAD_SUCCESS:"STATIC_SIGNUP_DATALOAD_SUCCESS",
    STATIC_SIGNUP_DATALOAD_FAILURE:"STATIC_SIGNUP_DATALOAD_FAILURE",

    //  user login with facebook
    ADD_FB_REQUEST: "ADD_FB_REQUEST",
    ADD_FB_SUCCESS: "ADD_FB_SUCCESS",
    ADD_FB_FAILURE: "ADD_FB_FAILURE",

    //  user login with facebook
    LOGIN_GMAIL_REQUEST: "LOGIN_GMAIL_REQUEST",
    LOGIN_GMAIL_SUCCESS: "LOGIN_GMAIL_SUCCESS",
    LOGIN_GMAIL_FAILURE: "LOGIN_GMAIL_FAILURE",

    //  user login with facebook
    LOGIN_APPLE_REQUEST: "LOGIN_APPLE_REQUEST",
    LOGIN_APPLE_SUCCESS: "LOGIN_APPLE_SUCCESS",
    LOGIN_APPLE_FAILURE: "LOGIN_APPLE_FAILURE",
}