
export default {
    Logo: require('./icons/logo3x.png'),
    backCrossIcon: require('./icons/cross3x.png'),
    arrowDown: require('./icons/arrowDown.png'),
    head1: require('./icons/head1.png'),
    center: require('./icons/cart_delivery.png'),
    mid1: require('./icons/mid1.png'),
    mid2: require('./icons/mid2.png'),
    tab1: require('./icons/tab1.png'),
    tab2: require('./icons/tab2.png'),
    tab3: require('./icons/tab3.png'),
    tab4: require('./icons/tab4.png'),
    tab5: require('./icons/tab5.png'),
    // headArb: require('./icons/head1.png'),
    centerArb: require('./icons/cart_delivery_arabic.png'),
    mid1Arb: require('./icons/cart_left.png'),
    mid2Arb: require('./icons/cart_right.png'),
    tab1Arb: require('./icons/tab_bar1.png'),
    tab2Arb: require('./icons/tab_bar2.png'),
    tab3Arb: require('./icons/tab_bar3.png'),
    tab4Arb: require('./icons/tab_bar4.png'),
    tab5Arb: require('./icons/tab_bar5.png'),
    markerLocation: require('./icons/markerLocation.png'),
    imgOffer3:require('./icons/imgOffer3.png'),
    imgOffer1:require('./icons/imgOffer1.png'),
    imgOffer2:require('./icons/imgOffer2.png'),
    pic_bg:require('./icons/pic_bg.png'),
    help_icon:require('./icons/Help.png'),
    refer_friend_head:require('./icons/referAfriend.png'),
}