export default {
    // COMMON IMAGE
    Splash: require('../assets/splash.png'),
    ProfileImg: require('../assets/campic.png'), 
    Logo:require('../assets/images/logo.png'),
    facebookIcon:require('../assets/images/facebookIcon.png'),
    socialIcon1:require('../assets/images/socialIcon1.png'),
    Ellipse:require('../assets/images/Ellipse.png'),
    Apple:require('../assets/images/Apple.png'),
    Google:require('../assets/images/Google.png'),
    Facebook:require('../assets/images/Facebook.png'),
    LoginLine:require('../assets/images/loginLine.png'),
    HomeMainBG: require('../assets/images/bg.png'),
    CharityBG: require('../assets/images/charityBG.png'),
    CharitySubBG1: require('../assets/images/charitySubscriptionBG1.png'),
    MainBanner: require('../assets/images/mainpagebanner.png'),
    MapMarker: require('../assets/images/mapMarker.png'),
    HangoutBanner: require('../assets/images/hangoutBanner.png'),
    imgMedia1: require('../assets/images/img_media@1.jpg'),
    imgMedia2: require('../assets/images/img_media@2.jpg'),
    imgMedia3: require('../assets/images/img_media@3.jpg'),
    imgMedia4: require('../assets/images/img_media@4.jpg'),
}