export default {
    LANGUAGE_REQUEST: "LANGUAGE_REQUEST",
    LANGUAGE_SUCCESS: "LANGUAGE_SUCCESS",
    LANGUAGE_FAILURE: "LANGUAGE_FAILURE",

    LANGUAGE_STORE_REQUEST: "LANGUAGE_STORE_REQUEST",
    LANGUAGE_STORE_SUCCESS: "LANGUAGE_STORE_SUCCESS",
    LANGUAGE_STORE_FAILURE: "LANGUAGE_STORE_FAILURE",

    AUTH_SEND_SMS_REQUEST: "AUTH_SEND_SMS_REQUEST",
    AUTH_SEND_SMS_SUCCESS: "AUTH_SEND_SMS_SUCCESS",
    AUTH_SEND_SMS_FAILURE: "AUTH_SEND_SMS_FAILURE",

    OTP_VERIFY_REQUEST: "OTP_VERIFY_REQUEST",
    OTP_VERIFY_SUCCESS: "OTP_VERIFY_SUCCESS",
    OTP_VERIFY_FAILURE: "OTP_VERIFY_FAILURE",

    GET_PRIVACY_REQUEST: "GET_PRIVACY_REQUEST",
    GET_PRIVACY_SUCCESS: "GET_PRIVACY_SUCCESS",
    GET_PRIVACY_FAILURE: "GET_PRIVACY_FAILURE",

    GET_TERMS_REQUEST: "GET_TERMS_REQUEST",
    GET_TERMS_SUCCESS: "GET_TERMS_SUCCESS",
    GET_TERMS_FAILURE: "GET_TERMS_FAILURE",

    VOICE_CALL_REQUEST: "VOICE_CALL_REQUEST",
    VOICE_CALL_SUCCESS: "VOICE_CALL_SUCCESS",
    VOICE_CALL_FAILURE: "VOICE_CALL_FAILURE",

    //  user profile Image upload type
    USER_PROFILE_IMAGE_UPLOAD_REQUEST: "USER_PROFILE_IMAGE_UPLOAD_REQUEST",
    USER_PROFILE_IMAGE_UPLOAD_SUCCESS: "USER_PROFILE_IMAGE_UPLOAD_SUCCESS",
    USER_PROFILE_IMAGE_UPLOAD_FAILURE: "USER_PROFILE_IMAGE_UPLOAD_FAILURE",

    //  user profile Set up data type
    USER_PROFILE_SETUP_DATA_REQUEST: "USER_PROFILE_SETUP_DATA_REQUEST",
    USER_PROFILE_SETUP_DATA_SUCCESS: "USER_PROFILE_SETUP_DATA_SUCCESS",
    USER_PROFILE_SETUP_DATA_FAILURE: "USER_PROFILE_SETUP_DATA_FAILURE",


    ADD_FB_REQUEST: "ADD_FB_REQUEST",
    ADD_FB_SUCCESS: "ADD_FB_SUCCESS",
    ADD_FB_FAILURE: "ADD_FB_FAILURE",

    // when a user open the app the static data will be load in the front end side
    GET_SPLASH_SCREEN_REQUEST: "GET_SPLASH_SCREEN_REQUEST",
    GET_SPLASH_SCREEN_SUCCESS: "GET_SPLASH_SCREEN_SUCCESS",
    GET_SPLASH_SCREEN_FAILURE: "GET_SPLASH_SCREEN_FAILURE",

    //  User Verify Otp Type
    VERIFY_OTP_REQUEST: "VERIFY_OTP_REQUEST",
    VERIFY_OTP_SUCCESS: "VERIFY_OTP_SUCCESS",
    VERIFY_OTP_FAILURE: "VERIFY_OTP_FAILURE",

    //  Resend  Verify Otp Type
    RESEND_VERIFY_OTP_REQUEST: "RESEND_VERIFY_OTP_REQUEST",
    RESEND_VERIFY_OTP_SUCCESS: "RESEND_VERIFY_OTP_SUCCESS",
    RESEND_VERIFY_OTP_FAILURE: "RESEND_VERIFY_OTP_FAILURE",
}
