export default {
    
    GET_SLIDER_IMAGE_REQUEST:"GET_SLIDER_IMAGE_REQUEST",
    GET_SLIDER_IMAGE_SUCCESS:"GET_SLIDER_IMAGE_SUCCESS",
    GET_SLIDER_IMAGE_FAILURE:"GET_SLIDER_IMAGE_FAILURE",

    CUSTOMER_REGISTRATION_REQUEST:"CUSTOMER_REGISTRATION_REQUEST",
    CUSTOMER_REGISTRATION_SUCCESS:"CUSTOMER_REGISTRATION_SUCCESS",
    CUSTOMER_REGISTRATION_FAILURE:"USTOMER_REGISTRATION_FAILURE",

    SOCIAL_REGISTRATION_REQUEST:"SOCIAL_REGISTRATION_REQUEST",
    SOCIAL_REGISTRATION_SUCCESS:"SOCIAL_REGISTRATION_SUCCESS",
    SOCIAL_REGISTRATION_FAILURE: "SOCIAL_REGISTRATION_FAILURE",
    
    SOCIAL_MEDIA_ID_REQUEST:"SOCIAL_MEDIA_ID_REQUEST",
    SOCIAL_MEDIA_ID_SUCCESS:"SOCIAL_MEDIA_ID_SUCCESS",
    SOCIAL_MEDIA_ID_FAILURE: "SOCIAL_MEDIA_ID_FAILURE",
    
    COUNTRY_CODE_REQUEST:"COUNTRY_CODE_REQUEST",
    COUNTRY_CODE_SUCCESS:"COUNTRY_CODE_SUCCESS",
    COUNTRY_CODE_FAILURE:"COUNTRY_CODE_FAILURE",

}
